# Configuration for RINEX file upload script
update_passwd_url: "https://api.geodesychile.usach.cl/user/update_password"
api_url: "https://api.geodesychile.usach.cl/upload/rinex"
token_url: "https://api.geodesychile.usach.cl/token"
